# Generated by Django 4.1.2 on 2022-10-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErroBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_erro', models.DateField(auto_created=True)),
                ('numero_pedido', models.IntegerField()),
                ('desconto_erros', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_pagamento', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=14)),
                ('ferias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcinarios.ferias')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcinarios.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_bonus', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('desconto_erros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcinarios.errobonus')),
            ],
        ),
    ]
