# Generated by Django 4.1.2 on 2022-10-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ferias',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ferias',
            field=models.ManyToManyField(to='funcinarios.ferias'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.ManyToManyField(to='funcinarios.pagamento'),
        ),
    ]
