# Generated by Django 4.1.2 on 2022-10-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0002_remove_funcionario_ferias_remove_funcionario_salario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='desconto_erros',
        ),
        migrations.AddField(
            model_name='bonus',
            name='desconto_erros',
            field=models.ManyToManyField(to='funcinarios.errobonus'),
        ),
    ]
