# Generated by Django 4.1.2 on 2022-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0003_remove_bonus_desconto_erros_bonus_desconto_erros'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='bonus',
            field=models.ManyToManyField(to='funcinarios.bonus'),
        ),
    ]
