# Generated by Django 4.1.2 on 2022-10-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0004_funcionario_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='bonus',
            field=models.ManyToManyField(related_name='bonus', to='funcinarios.bonus'),
        ),
    ]
