# Generated by Django 4.1.2 on 2022-10-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0005_alter_funcionario_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='desconto_erros',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ferias',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.pagamento'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.funcionario'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.funcionario'),
        ),
    ]
