# Generated by Django 4.1.2 on 2022-10-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0006_remove_bonus_desconto_erros_remove_funcionario_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adiantamento', models.DateField(auto_created=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.pagamento')),
            ],
        ),
    ]
