# Generated by Django 4.1.2 on 2022-10-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0007_adiantamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adiantamento',
            old_name='Pagamento',
            new_name='pagamento',
        ),
    ]
