# Generated by Django 4.1.2 on 2022-10-25 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0008_rename_pagamento_adiantamento_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiantamento',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.funcionario'),
        ),
    ]
