# Generated by Django 4.1.2 on 2022-10-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0009_alter_adiantamento_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adiantamento',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ferias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.ferias'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='adiantamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.adiantamento'),
        ),
    ]
