# Generated by Django 4.1.2 on 2022-10-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0011_remove_funcionario_ferias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiantamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
