# Generated by Django 4.1.2 on 2022-10-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0013_remove_pagamento_adiantamento_adiantamento_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='errobonus',
            name='bonus_erro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.bonus'),
        ),
    ]
