# Generated by Django 4.1.2 on 2022-10-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0014_errobonus_bonus_erro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='bonus',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='bonus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.bonus'),
        ),
    ]
