# Generated by Django 4.1.2 on 2022-10-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcinarios', '0015_remove_bonus_bonus_pagamento_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcinarios.bonus'),
        ),
    ]
