# Generated by Django 4.1.2 on 2022-10-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_geral'),
        ('funcinarios', '0018_extras_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.geral'),
        ),
    ]
