# Generated by Django 4.1.2 on 2022-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='geral',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
