# Generated by Django 4.1.2 on 2022-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_geral_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='geral',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
