# Generated by Django 4.1.2 on 2022-10-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_geral_valor_bruto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geral',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
